import React from 'react';

const Tos = () => {
  return (
    <main className='main-container'>
      <h1>Terms of Service for Sasquatch Bot</h1>
      <p><strong>Effective Date</strong>: September 12, 2024</p>

      <h2>1. Introduction</h2>
      <p>
        Welcome to Sasquatch Bot, a Discord bot that enhances your server experience by providing statistical analysis, 
        moderation tools, and more. By using Sasquatch Bot, you agree to the following terms of service (hereinafter 
        referred to as "Terms"). If you do not agree to these Terms, please refrain from using the bot.
      </p>

      <h2>2. Data Collection and Usage</h2>
      <p>
        Sasquatch Bot collects and stores the following data for the purpose of statistical analysis, message moderation, 
        and server management:
      </p>
      <ul>
        <li><strong>User Data</strong>: User IDs and usernames.</li>
        <li><strong>Server Data</strong>: Server names and server IDs.</li>
        <li><strong>Channel Data</strong>: Channel names and channel IDs.</li>
      </ul>
      <p>
        This data is used for generating server statistics, monitoring bot performance, and displaying analytics on 
        the website and Discord. Additionally, moderation features such as muting, kicking, banning, and message 
        filtering utilize user and server data for appropriate actions.
      </p>

      <h2>3. Storage and Security</h2>
      <p>
        All collected data is securely stored using Google Firestore, a cloud-based database solution. The bot uses 
        an API to transmit data from the database to the website for statistical analysis. We implement security 
        measures to protect your data from unauthorized access or disclosure, but we cannot guarantee absolute 
        security due to the nature of online services.
      </p>

      <h2>4. Moderation Features</h2>
      <p>
        Sasquatch Bot includes the ability to mute, kick, ban, filter, and delete messages that contain profanity or 
        inappropriate content. These actions are at the discretion of the server administrators and moderators. 
        Sasquatch Bot does not assume responsibility for any misuse of these features.
      </p>
      <ul>
        <li><strong>Mute</strong>: Temporarily prevents a user from participating in voice or text channels.</li>
        <li><strong>Kick</strong>: Removes a user from the server.</li>
        <li><strong>Ban</strong>: Permanently removes a user and prevents them from rejoining the server.</li>
        <li><strong>Message Filtering</strong>: The bot can automatically detect and delete messages containing 
        profanity or other undesirable content based on server-defined rules.</li>
      </ul>
      <p>
        By using these features, you acknowledge that you have the necessary permissions to perform such actions 
        in the server.
      </p>

      <h2>5. Data Sharing and Retention</h2>
      <p>
        The data collected by Sasquatch Bot will not be shared with third parties except as required by law. We retain 
        your data for as long as necessary to provide the services offered by Sasquatch Bot and to comply with legal 
        obligations. You may request the removal of your data by contacting the server administrator or <a href="mailto:discordsasquatchbot@gmail.com">discordsasquatchbot@gmail.com</a>.
      </p>

      <h2>6. User Responsibilities</h2>
      <p><strong>Proper Use</strong>: You agree to use Sasquatch Bot as intended and in accordance with these Terms. You are prohibited 
      from attempting to exploit any flaws, vulnerabilities, or unintended behaviors of the bot. Abuse or exploitation of the bot 
      may result in removal from your server or a ban on its use.</p>
      <p><strong>Language and Content</strong>: You are responsible for any language, content, or behavior caused by your use of the bot. 
      This includes situations where users trigger automatic responses or actions from the bot. Sasquatch Bot and its developers are not liable 
      for any inappropriate language or content generated by user actions.</p>

      <h2>7. Liability</h2>
      <p>
        Sasquatch Bot and its developers are not liable for any loss, damage, or harm caused by the use of the bot, 
        including but not limited to issues arising from the bot’s moderation features, message filtering, or 
        data analysis functions. Use of the bot is at your own risk.
      </p>

      <h2>8. Updates to Terms</h2>
      <p>
        We may modify these Terms at any time. Any changes will be posted to Sasquatch Bot's official website or 
        announced in the support Discord server. Continued use of the bot following such updates constitutes your 
        acceptance of the revised Terms.
      </p>

      <h2>9. Contact Information</h2>
      <p>
        If you have any questions about these Terms or the bot, please contact us at <a href="mailto:discordsasquatchbot@gmail.com">discordsasquatchbot@gmail.com</a>.
      </p>

      <p>
        By adding Sasquatch Bot to your server or using its features, you agree to abide by these Terms of Service.
      </p>
    </main>
  );
};

export default Tos;
